# Data curation

Goal: Process the data from the raw database to make it ready for data analysis. This new database will be called prod

In [49]:
# Data curation
import sqlite3

# Used for pretty printing
import pandas as pd

# Creating empty data base
con = sqlite3.connect("unified.db")
cur = con.cursor()

# Enable REGEX for sqlite
import re


def regexp(expr, item):
    reg = re.compile(expr)
    return reg.search(item) is not None

con.create_function("REGEXP", 2, regexp)

# Create new table and check for multiple executions
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='prod'")
if not cur.fetchone():  # If the fetch returns None, table does not exist
    cur.execute("CREATE TABLE prod AS SELECT * FROM initial")
    print("Table 'prod' created successfully.")
else:
    print("Table 'prod' already exists.")

OperationalError: near "IF": syntax error

## Valid sequences

Check wether sequence only contains valid amino acids and no whitespaces or any other letters not being valid AA's.

In [48]:
# This query checks if there are any symbols other the the valid aa code
pd.read_sql_query("""SELECT *
                FROM initial
                WHERE seq REGEXP '[^ARNDCEQGHILKMFPSTWYVX]'; 
""", con)
 # WHERE seq REGEXP '[^ARNDCEQGHILKMFPSTWYV]'; to not include X

,id,name,AB,description,OX,dataset,seq,seq_len
0,L11A004522,LAMP2_L11A004522,1,None,alien,LAMP2.fasta,kklaklallkwllalkklallalkk,25
1,L13A15655,LAMP2_L13A15655,1,None,alien,LAMP2.fasta,kklfkkilkyL,11
2,DRAMP20856,dramp_DRAMP20856,1,None,alien,dramp_antimicrobial.fasta,OWOWOWORPVYOPRPRPPHPRL,22
3,DRAMP20857,dramp_DRAMP20857,1,None,alien,dramp_antimicrobial.fasta,OIOIORPVYOPRPRPPHPRL,20
4,DRAMP21410,dramp_DRAMP21410,1,None,alien,dramp_antimicrobial.fasta,klckivvikvck,12
...,...,...,...,...,...,...,...,...
88,P21986,FLA3_SPIAU,0,Flagellar filament 32 kDa core protein (Fragme...,Spirochaeta aurantia OX=147,uniprot_swissprot.fasta,MIINHNMSAINANRVLGBT,19
89,P21987,FLA4_SPIAU,0,Flagellar filament 31.5 kDa core protein (Frag...,Spirochaeta aurantia OX=147,uniprot_swissprot.fasta,MIINHNMSAINANRVLGBTNADITKDL,27
90,P25072,PA21_MICTM,0,Phospholipase A2 1 (Fragment),Micrurus tener microgalbineus OX=8636,uniprot_swissprot.fasta,SLLBFKBMIEST,12
91,P35707,FLAV_NOSSM,0,Flavodoxin (Fragment),Nostoc sp. (strain MAC) OX=35822,uniprot_swissprot.fasta,SKKIGLFYGTZTGKTESVAEIIDEFGDEVVTLDID,35
92,P56531,VIT_MELGA,0,Phosvitin (Fragment),Meleagris gallopavo OX=9103,uniprot_swissprot.fasta,AELGTEPNAKTSSSSSSVSSTATSSSSSSASSPBRKKPMD,40

Problems found in seq:
* non capitalized letters
* the letter X

## Duplicates
Check wether there are duplicates

In [20]:
pd.read_sql_query("""SELECT seq, COUNT(seq)
                FROM initial
                GROUP BY seq
                HAVING COUNT(seq) > 1;
""", con)

          seq  COUNT(seq)
0  FALALKAKKL       12864